 //take the userid to make a get request ffrom the backend and we need the token for the request
 export const read = (Id, token) => {

    return fetch(`${process.env.REACT_APP_API_URL}/api/user/${Id}`, {
        method: "GET",
        headers: {
            Accept: "application/json",
            "Content-Type": "application/json",
            //a cryptic string, generated by the server in response to a login request.
            //used mainly for documentation purposes, as a hint to the clients
            Authorization: `Bearer ${token}`
        }
    })
    //response of the fetch
    .then(res => {
        return res.json()

    })
    .catch(err => console.log(err));
};

export const update = (Id, token, user) => {

    return fetch(`${process.env.REACT_APP_API_URL}/api/user/${Id}`, {
        method: "PUT",
        headers: {
            Accept: "application/json",
            "Content-Type": "application/json",
            //a cryptic string, generated by the server in response to a login request.
            //used mainly for documentation purposes, as a hint to the clients
            Authorization: `Bearer ${token}`
        }, 
        body: JSON.stringify(user)
    })
    //response of the fetch
    .then(res => {
        return res.json()

    })
    .catch(err => console.log(err));
};


 
 export const remove = (Id, token) => {

    return fetch(`${process.env.REACT_APP_API_URL}/api/user/${Id}`, {
        method: "DELETE",
        headers: {
            Accept: "application/json",
            "Content-Type": "application/json",
            Authorization: `Bearer ${token}`
        }
    })
 
    .then(res => {
        return res.json();

    })
    .catch(err => console.log(err));
};

export const list = () => {

    return fetch(`${process.env.REACT_APP_API_URL}/api/users`, {
        method: "GET",
    })
    //response of the fetch
    .then(res => {
        return res.json()

    })
    .catch(err => console.log(err));
};

